### PR TITLE
fix: CHF panics on wrong ChargingDataRef in partial-record reopen

### LINKED ISSUE #950: Bugs] CHF POST /nchf-convergedcharging/v3/chargingdata/{ChargingDataRef}/update panics on wrong ChargingDataRef in partial-record reopen
## Bug Decription
`CHF`'s authenticated `POST /nchf-convergedcharging/v3/chargingdata/{ChargingDataRef}/update` path can panic when a wrong `ChargingDataRef` is used after multiple charging sessions already exist for the same `subscriberIdentifier`.

The issue is stateful:

1. create at least two charging sessions for the same `subscriberIdentifier`
2. send an `update` request for that subscriber with a bogus `ChargingDataRef`
3. `ChargingDataUpdate()` still proceeds because it falls back to the most recent record when `len(ue.Records) > 1`
4. if the request reaches the partial-record reopen path, `OpenCDR(..., partialRecord=true)` looks up `ue.Cdr[chargingSessionId]` using the bogus ref
5. the map lookup returns `nil`, and `OpenCDR()` dereferences it, causing a panic

This is a confirmed panic sink in the partial-record reopen path, triggered by mismatched in-memory record selection and session-key lookup.

## To Reproduce
1. Produce a valid `nchf-convergedcharging` bearer token. In this validation an offline `RS512` JWT signed with `/home/ubuntu/free5gc_v421/free5gc/cert/nrf.key` was used.
2. Create a first charging session for a fresh subscriber, for example:

```json
{
  "subscriberIdentifier": "imsi-208930000000889",
  "chargingId": 1,
  "nfConsumerIdentification": {
    "nodeFunctionality": "SMF",
    "nFName": "smfA",
    "nFIPv4Address": "10.100.200.6"
  },
  "invocationTimeStamp": "2026-03-27T01:00:00Z",
  "invocationSequenceNumber": 1,
  "multipleUnitUsage": [
    {
      "ratingGroup": 1,
      "requestedUnit": {
        "totalVolume": 1
      },
      "usedUnitContainer": [
        {
          "quotaManagementIndicator": "ONLINE_CHARGING",
          "totalVolume": 1
        }
      ]
    }
  ],
  "triggers": [
    {
      "triggerType": "VOLUME_LIMIT",
      "triggerCategory": "IMMEDIATE_REPORT"
    }
  ]
}
```

3. Create a second charging session for the same subscriber but a different `nFName`, for example `smfB`.
4. Reuse that subscriber state and send an update with a bogus `ChargingDataRef` such as:

```text
POST /nchf-convergedcharging/v3/chargingdata/does-not-exist-partial/update
```

with a body such as:

```json
{
  "subscriberIdentifier": "imsi-208930000000889",
  "chargingId": 1,
  "nfConsumerIdentification": {
    "nodeFunctionality": "SMF",
    "nFName": "smfB",
    "nFIPv4Address": "10.100.200.6"
  },
  "invocationTimeStamp": "2026-03-27T01:00:00Z",
  "invocationSequenceNumber": 3,
  "multipleUnitUsage": [
    {
      "ratingGroup": 1,
      "requestedUnit": {
        "totalVolume": 1
      },
      "usedUnitContainer": [
        {
          "quotaManagementIndicator": "ONLINE_CHARGING",
          "totalVolume": 1
        }
      ]
    }
  ],
  "triggers": [
    {
      "triggerType": "VOLUME_LIMIT",
      "triggerCategory": "IMMEDIATE_REPORT"
    }
  ]
}
```

5. Observe:

```text
HTTP/1.1 500 Internal Server Error
```

6. Inspect `chf` logs and confirm the panic in `OpenCDR()` at `cdr.go:36`.

## Expected Behavior
`CHF` should reject an unknown `ChargingDataRef` before it can reach the partial-record reopen path.

Expected behavior:

- if `ue.Cdr[chargingSessionId]` does not exist, return a controlled error
- do not fall back to `ue.Records[last]` for a mismatched charging-session key
- do not dereference `ue.Cdr[wrongRef]` inside `OpenCDR(partialRecord=true)`

## Screenshots
N/A

## Environment
- free5GC Version: `v4.2.1`
- OS: `Ubuntu 22.04 (Jammy Jellyfish)`
- Kernel version: `5.15.0-88-generic`
- go version: `go1.24.9 linux/amd64`
- Runtime image: `free5gc/chf:v4.2.1`
- Runtime CHF commit hash: `5dabc81f`
- Validation date: `2026-03-27`

### Log File
Relevant `docker logs` excerpt:

```text
2026-03-26T16:41:00.101071421Z [INFO][CHF][GIN] | 201 | 10.100.200.1 | POST | /nchf-convergedcharging/v3/chargingdata |
2026-03-26T16:41:00.143962804Z [INFO][CHF][GIN] | 201 | 10.100.200.1 | POST | /nchf-convergedcharging/v3/chargingdata |
2026-03-26T16:41:10.576876826Z [ERRO][CHF][GIN] panic: runtime error: invalid memory address or nil pointer dereference
github.com/free5gc/chf/internal/sbi/processor.(*Processor).OpenCDR
    /go/src/free5gc/NFs/chf/internal/sbi/processor/cdr.go:36 +0x1062
github.com/free5gc/chf/internal/sbi/processor.(*Processor).ChargingDataUpdate
    /go/src/free5gc/NFs/chf/internal/sbi/processor/converged_charging.go:316 +0x93d
2026-03-26T16:41:10.576933074Z [INFO][CHF][GIN] | 500 | 10.100.200.1 | POST | /nchf-convergedcharging/v3/chargingdata/does-not-exist-partial/update |
```

### PR DESCRIPTION
**Pull request by solar224**
- Fixes a panic when a wrong ChargingDataRef is used in partial-record flows.
- Adds session validation in ChargingDataUpdate: unknown or nil charging-session context returns a controlled 404 ProblemDetails.
- Removes the unsafe fallback to the latest record and keeps ue.Cdr[chargingSessionId] aligned during partial-record rollover.
- Hardens OpenCDR(..., partialRecord=true) with defensive nil/session checks.
- Adds tests.

Fixes: free5gc/free5gc#950

### CODE REVIEW

**Review by c9274326 — APPROVED** [review]
@Alonza0314 LGTM

File: internal/sbi/processor/converged_charging.go [hunk 1]
```diff
@@ -240,15 +241,22 @@ func (p *Processor) ChargingDataUpdate(
...
+		}
+		return nil, problemDetails
+	}
+
 	// Online charging: Rate, Account, Reservation
 	responseBody, partialRecord := p.BuildConvergedChargingDataUpdateResopone(chargingData)
 
-	cdr := ue.Cdr[chargingSessionId]
-
-	if len(ue.Records) > 1 {
```
Comment (Alonza0314) [inline internal/sbi/processor/converged_charging.go:248]: Why we removed this fallback machanism?

Comment (solar224) [reply internal/sbi/processor/converged_charging.go:248]: I removed this fallback on purpose because it could hide an invalid ChargingDataRef and reopen or update the wrong CDR. If chargingSessionId is not found, picking ue.Records[len-1] is non-deterministic and may cause cross-session corruption or panic in the partial-reopen path.
So now fail fast with 404 for unknown references.

**Review by Alonza0314 — APPROVED** [review]
